import type { Site } from '../src/types';

export const mockSites: Site[] = [
  {
    siteId: 'SITE-001',
    siteName: 'Sunnyvale Commercial Plaza',
    siteStage: 'Active',
    siteStatus: 'Normal',
    lastIntervalEndDate: '2024-07-15T23:45:00Z',
    microCount: 120,
    envoyCount: 4,
    miProductSku: 'IQ8A-72-2-US',
    envoyType: 'IQ Gateway Commercial',
    installerName: 'SolarTech Pro',
    state: 'California',
    country: 'United States',
    connectionType: 'Ethernet',
    severity: 'No Severity',
    systemSize: 48.0,
    activationDate: '2023-01-15',
  },
  {
    siteId: 'SITE-002',
    siteName: 'Austin Office Complex',
    siteStage: 'Active',
    siteStatus: 'Warning',
    lastIntervalEndDate: '2024-07-15T23:30:00Z',
    microCount: 200,
    envoyCount: 6,
    miProductSku: 'IQ8A-72-2-US',
    envoyType: 'IQ Gateway Commercial',
    installerName: 'GreenEnergy Solutions',
    state: 'Texas',
    country: 'United States',
    connectionType: 'Ethernet',
    severity: 'S2',
    systemSize: 80.0,
    activationDate: '2022-11-20',
  },
  {
    siteId: 'SITE-003',
    siteName: 'Portland Warehouse District',
    siteStage: 'Active',
    siteStatus: 'Critical',
    lastIntervalEndDate: '2024-07-14T18:00:00Z',
    microCount: 350,
    envoyCount: 10,
    miProductSku: 'IQ7PLUS-72-2-US',
    envoyType: 'IQ Gateway Commercial',
    installerName: 'Pacific Solar',
    state: 'Oregon',
    country: 'United States',
    connectionType: 'WiFi',
    severity: 'S0',
    systemSize: 140.0,
    activationDate: '2021-06-10',
  },
  {
    siteId: 'SITE-004',
    siteName: 'Denver Industrial Park',
    siteStage: 'Active',
    siteStatus: 'Normal',
    lastIntervalEndDate: '2024-07-15T23:45:00Z',
    microCount: 80,
    envoyCount: 3,
    miProductSku: 'IQ8M-72-2-US',
    envoyType: 'IQ Gateway',
    installerName: 'Mountain Solar Inc',
    state: 'Colorado',
    country: 'United States',
    connectionType: 'Ethernet',
    severity: 'No Severity',
    systemSize: 32.0,
    activationDate: '2023-08-05',
  },
  {
    siteId: 'SITE-005',
    siteName: 'Miami Retail Center',
    siteStage: 'Active',
    siteStatus: 'Warning',
    lastIntervalEndDate: '2024-07-15T22:00:00Z',
    microCount: 150,
    envoyCount: 5,
    miProductSku: 'IQ8A-72-2-US',
    envoyType: 'IQ Gateway Commercial',
    installerName: 'Sunshine Energy',
    state: 'Florida',
    country: 'United States',
    connectionType: 'Cellular',
    severity: 'S3',
    systemSize: 60.0,
    activationDate: '2022-03-22',
  },
  {
    siteId: 'SITE-006',
    siteName: 'Chicago Distribution Hub',
    siteStage: 'Active',
    siteStatus: 'Normal',
    lastIntervalEndDate: '2024-07-15T23:45:00Z',
    microCount: 250,
    envoyCount: 8,
    miProductSku: 'IQ8A-72-2-US',
    envoyType: 'IQ Gateway Commercial',
    installerName: 'Midwest Solar Group',
    state: 'Illinois',
    country: 'United States',
    connectionType: 'Ethernet',
    severity: 'S4',
    systemSize: 100.0,
    activationDate: '2022-09-14',
  },
  {
    siteId: 'SITE-007',
    siteName: 'Phoenix Tech Campus',
    siteStage: 'Active',
    siteStatus: 'Offline',
    lastIntervalEndDate: '2024-07-10T12:00:00Z',
    microCount: 180,
    envoyCount: 6,
    miProductSku: 'IQ7A-72-2-US',
    envoyType: 'Envoy-S',
    installerName: 'Desert Sun Power',
    state: 'Arizona',
    country: 'United States',
    connectionType: 'WiFi',
    severity: 'S1',
    systemSize: 72.0,
    activationDate: '2021-12-01',
  },
  {
    siteId: 'SITE-008',
    siteName: 'Seattle Innovation Center',
    siteStage: 'Active',
    siteStatus: 'Normal',
    lastIntervalEndDate: '2024-07-15T23:45:00Z',
    microCount: 90,
    envoyCount: 3,
    miProductSku: 'IQ8M-72-2-US',
    envoyType: 'IQ Gateway',
    installerName: 'Evergreen Solar',
    state: 'Washington',
    country: 'United States',
    connectionType: 'Ethernet',
    severity: 'No Severity',
    systemSize: 36.0,
    activationDate: '2024-01-10',
  },
  {
    siteId: 'SITE-009',
    siteName: 'New York Commercial Tower',
    siteStage: 'Active',
    siteStatus: 'Warning',
    lastIntervalEndDate: '2024-07-15T21:00:00Z',
    microCount: 300,
    envoyCount: 9,
    miProductSku: 'IQ8A-72-2-US',
    envoyType: 'IQ Gateway Commercial',
    installerName: 'Empire Solar',
    state: 'New York',
    country: 'United States',
    connectionType: 'Ethernet',
    severity: 'S2',
    systemSize: 120.0,
    activationDate: '2022-05-18',
  },
  {
    siteId: 'SITE-010',
    siteName: 'Atlanta Logistics Center',
    siteStage: 'Inactive',
    siteStatus: 'Offline',
    lastIntervalEndDate: '2024-06-30T12:00:00Z',
    microCount: 100,
    envoyCount: 3,
    miProductSku: 'IQ7PLUS-72-2-US',
    envoyType: 'Envoy-S',
    installerName: 'Southern Solar Co',
    state: 'Georgia',
    country: 'United States',
    connectionType: 'WiFi',
    severity: 'S1',
    systemSize: 40.0,
    activationDate: '2020-08-25',
  },
];
